# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Featured Posts
  description: Featured stories grid
  icon: "chrome_reader_mode"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  main_feature: ""
  feature_list: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: