# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Text Block"
  description: Simple text block
  icon: description
  tags:
    - Text
    - Colors

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#ffffff'
  heading:
    text_content:
    text_color: '#333232'
  layout:
    text_alignment: center
    column_alignment: center
    column_number: 1
  text_color: '#333232'
  text_content:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  heading:
    type: object
    options:
      preview:
        icon: short_text
  layout:
    hidden: false
    options:
      preview:
        icon: align_horizontal_center
  column_number:
    type: range
    options:
      min: 1
      max: 4
      step: 1
  text_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
  column_alignment:
    type: select
    options:
      values:
        - start
        - center
        - end
  
