# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Post Hero
  description: 
  icon: 'space_dashboard'
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: