# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left Right
  description: Left Right block
  icon: 'chrome_reader_mode'
  tags: ['block', 'left-right']

# Defines the structure of this component, as well as the default values
blueprint:
  bg_image:
  heading:
  text:
  image:
  image_alt:
  button: bookshop:global/button

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
